### PR TITLE
Allow themes to have user-customizable color pickers, take two

### PR DESCRIPTION
**Pull request by j0sh77**
(Original PR: #27, rebased due to too many changes and just opened a new one)

This PR adds the ability for theme developers to add CSS colors that are customizable by the user.

By adding any amount of "colors" to the theme:
```
jround: { 
  text: 'Round', 
  colors: { 
    background: {r: 0, g: 0, b: 0, a: 0.3} 
  }
},
```

User's will be able to modify the colors added in the "General" tab.

Capture
Capture

These variables are accessible in theme scss files by using the variable `--color-theme-X`, where `X` is the key name in the colors object.

These UI changes are only visible for themes that have custom colors.

See this in action in a new theme! https://github.com/j0sh77/skyline-overlay/pull/1

### CODE REVIEW

**Comment by j0sh77** [comment]
Hey @dsrkafuu, I got #27 all rebased and opened it here. If you have any concerns, let me know!

I opened a PR in my fork for a new theme that relies on this functionality more and I'll re-open it here once this merges. It was a bit difficult to read in a previous PR here, so I'll just wait. 😄 https://github.com/j0sh77/skyline-overlay/pull/1

**Comment by j0sh77** [comment]
For anyone reviewing, I know it's a lengthier PR, so I'm happy to walk through this with anyone on Discord if needed. 😄

**Comment by dsrkafuu** [comment]
@j0sh77 Sorry for the long time no reply.

I am in the process of merging the PR into the `dev` branch and I plan to make the following adjustments based on this PR in the near future:

1. Create a new settings panel for changing color settings
2. Support setting theme colors (of course)
3. Support setting specific color for each job or color for job categories
4. Provide some color presets

**Comment by j0sh77** [comment]
@dsrkafuu No worries! I appreciate the time. 😄 If you want help with any of those, feel free to make tasks and I'll do my best to match your style preferences. 

> Support setting specific color for each job or color for job categories

Also, this would be awesome. I like the idea.

**Pull request merged**
